#Variables
first_name = input('First name: ').capitalize()
last_name = input('Last name: ').upper()
email_address = input('Email Address: ').lower()
phone_number = input('Phone Number: ')
job_title = input('Job Title: ').capitalize()
id_number = input('ID Number: ')
hair_color = input('Hair color: ')
eye_color = input('Eye color: ')
month_started = input('Month started: ')
advanced_training = input('Advanced training: [Yes/No] ')


print('----------------------------------------')
print(f"{last_name}, {first_name}")
print(f"{job_title}")
print(f"{id_number}")
print(" ")
print(email_address)
print(phone_number)
print('')
print(f'Hair:  {hair_color}       Eyes: {eye_color}')
print(f'Month: {month_started}       Training: {advanced_training}')
print('----------------------------------------')
