print('Please enter the following: ')
print("")
adjective = input('adjective: ')
animal = input('animal: ')
verb = input('verb: ')
exclamation = input('exclamation: ').capitalize()
verb2 = input('verb: ')
verb3 = input('verb: ')
verb4pasttense = input('verb in past tense: ')
noun = input('noun: ')
print('')
print('Your story is:')
print('')
print(f'The other day, I was really in trouble. It all started when I saw a very {adjective} {animal} {verb} down the hallway. "{exclamation}!" I yelled. But all I could think to do was to {verb2} over and over. Miraculously, that caused it to stop, but not before it tried to {verb3} right in front of my family. Then it {verb4pasttense} right on my car. It then ate my {noun}')
